### ISSUE TITLE
npm test ошибки в сборке

### ISSUE THREAD

**Issue by NikolayLemehov** [htmlonelove/liga-pug-template#6]
Предлагаю:
1. чтобы убрать ошибки `npm test` в` .editorconfig` добавить исключение `[polyfill-object-fit.js] indent_style = tab`, поправить отступы и убрать лишние строки в конце файла. **Пулреквест**: https://github.com/htmlonelove/liga-pug-template/pull/4
2. чтобы убрать ошибки `npm test` (обнаружены мной только в выполняемом проекте, в сборке не обнаружил)  в `.stylelintrc`, поднял версию _stylelint_ до **13.13.0** (помогло, ушли ошибки по всем стилям одинаковые https://prnt.sc/15ldghr и добавил правило `"max-nesting-depth": null`.

**Comment by htmlonelove** [comment]
1. поправим правильно отредактировав файл, а не создавая исключение
2. линтер обновим
