### ISSUE TITLE
gulpfile - возможность наблюдать у copypngjpg так же и за webp

### ISSUE THREAD

**Issue by NikolayLemehov** [htmlonelove/liga-pug-template#7]
Я в очередной раз делал `webp` и в очередной раз, чтобы они заработали (попали в `build`) мне нужно перезапустить проект, чтобы сработал `gulp.copy` который скопирует всю папку `img`
Будет здорово, если `watch`, который следит за `png` и `jpg` также следил и за `webp`. Это позволит делать `webp` и позволит избавиться от лишнего перезапуска проекта.
Предлагаю следующие https://prnt.sc/15smua1 изменения.
**Пулреквест**: https://github.com/htmlonelove/liga-pug-template/pull/5

**Comment by justforthesoul** [comment]
Добавили
